[project]
name = "module-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.4",
    "minsearch>=0.0.7",
    "requests>=2.31.0",
]
